const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '../data');
const ARTIFACTS_DIR = path.join(DATA_DIR, 'artifacts');
const PROJECTS_FILE = path.join(DATA_DIR, 'projects.json');

const AGENTS = ['analyst', 'strategist', 'architect', 'qaqc', 'devops', 'taskmaster'];

function calculateMetrics() {
    if (!fs.existsSync(PROJECTS_FILE)) {
        console.error('Projects file not found.');
        return;
    }

    const projects = JSON.parse(fs.readFileSync(PROJECTS_FILE, 'utf8'));
    let totalExpectedArtifacts = projects.length * AGENTS.length;
    let totalGeneratedArtifacts = 0;
    
    let tp = 0; // True Positives: Successful generations with content
    let fp = 0; // False Positives: Generated but empty/failed-schema
    let fn = 0; // False Negatives: Not generated but expected

    projects.forEach(project => {
        const artifactPath = path.join(ARTIFACTS_DIR, project.id);
        
        AGENTS.forEach(agent => {
            const file = path.join(artifactPath, `${agent}.json`);
            if (fs.existsSync(file)) {
                totalGeneratedArtifacts++;
                try {
                    const content = JSON.parse(fs.readFileSync(file, 'utf8'));
                    // Check if it has actual content (simplified heuristic)
                    const hasContent = checkContent(agent, content);
                    if (hasContent) {
                        tp++;
                    } else {
                        fp++;
                    }
                } catch (e) {
                    fp++;
                }
            } else {
                fn++;
            }
        });
    });

    // Accuracy = (TP + TN) / (TP + TN + FP + FN) 
    // Since we don't have TN (True Negatives - should not have generated), 
    // we use a simplified version for system reliability.
    const accuracy = (tp / totalExpectedArtifacts) * 100;
    const precision = (tp / (tp + fp)) * 100 || 0;
    const recall = (tp / (tp + fn)) * 100 || 0;
    const f1 = 2 * (precision * recall) / (precision + recall) || 0;

    return {
        accuracy: accuracy.toFixed(2),
        precision: precision.toFixed(2),
        recall: recall.toFixed(2),
        f1Score: f1.toFixed(2),
        stats: {
            totalProjects: projects.length,
            totalGenerated: totalGeneratedArtifacts,
            totalExpected: totalExpectedArtifacts,
            tp, fp, fn
        }
    };
}

function checkContent(agent, content) {
    if (!content) return false;
    
    // Heuristic: check for non-empty lists or strings in key fields
    if (agent === 'analyst') {
        return content.sections?.functionalRequirements?.length > 0 || content.sections?.userStories?.length > 0;
    }
    if (agent === 'strategist') {
        return content.sections?.phases?.length > 0;
    }
    if (agent === 'architect') {
        return content.sections?.components?.length > 0;
    }
    if (agent === 'qaqc') {
        return content.sections?.testCases?.length > 0;
    }
    if (agent === 'devops') {
        return content.sections?.pipelineSteps?.length > 0;
    }
    if (agent === 'taskmaster') {
        return content.sections?.tasks?.length > 0;
    }
    return true;
}

const results = calculateMetrics();

if (results) {
    const report = `
# 📊 Performance Metrics Report

This report summarizes the performance of the **Nexus SDLC Orchestrator** Multi-Agent Swarm based on current project data.

## 📈 System Metrics

| Metric | Score | Description |
| :--- | :--- | :--- |
| **Accuracy** | ${results.accuracy}% | Overall reliability of the pipeline completion. |
| **Precision** | ${results.precision}% | Ratio of high-quality, content-rich artifact generation. |
| **Recall** | ${results.recall}% | Ability to capture all required SDLC stages. |
| **F1 Score** | ${results.f1Score}% | Harmonic mean of Precision and Recall. |

## 🔍 Data Insights

- **Total Projects Processed**: ${results.stats.totalProjects}
- **Successful Generations (TP)**: ${results.stats.tp}
- **Partial/Empty Generations (FP)**: ${results.stats.fp}
- **Missing Generations (FN)**: ${results.stats.fn}
- **Total Expected Artifacts**: ${results.stats.totalExpected}

---
*Generated by Performance Evaluator v1.0*
`;

    fs.writeFileSync(path.join(__dirname, '../../PERFORMANCE_METRICS.md'), report);
    console.log('Performance report generated: PERFORMANCE_METRICS.md');
}
